# Generated by Django 4.2.7 on 2023-12-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_users_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
